services:

  mongodb:
    image: mongo
    restart: always
    ports:
      - ${MONGODB_PORT:-27017}:27017
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME:-library}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD:-password}
    volumes:
      - ./db/mongo:/data/db

  mongo_express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT:-8081}:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USERNAME:-root}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD:-password}
    depends_on:
      - mongodb

  delivery:
    image: node:18.16
    volumes:
      - ./delivery/app:/app
    working_dir: /app
    environment:
      - PORT=80
      - DB_URL=mongodb://${DB_USERNAME:-root}:${DB_PASSWORD:-password}@mongodb:${MONGODB_PORT:-27017}/${DB_NAME:-library}
      - COOKIE_SECRET=${COOKIE_SECRET:-COOKIE_SECRET}
    ports:
      - ${DELIVERY_SERVICE_PORT:-3002}:80
    command: bash -c "npm install && npm run dev"
    depends_on:
      - mongodb

